added mtns from Akshay's branches
CliMA/ClimaCore.jl pull request #1049
Opened 2022-12-13 18:21 UTC by bischtob

This PR aims to add two mountain test cases to the main branch.

1. Agnesis Mountain (nonhydrostatic + total energy)
2. Schar Mountain (nonhydrostatic + total energy)

This allows other users to access generic box mountain test cases for experimentation with new formulations of the equations.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

2022-12-13 18:32 UTC, bischtob commented
bors try

2022-12-13 18:47 UTC, valeriabarra commented on examples/hybrid/plane/topo_agnesi_nh.jl
> +    #@. dw -= Ic2f(βx) * fw
I would remove stale comments and the related unused `rayleigh_sponge_x` function

2022-12-13 19:02 UTC, valeriabarra commented
I can't comments on the artifacts produced, but this seems to be weird Schar Mountain's contravariant3.mp4 seems very weird

2022-12-13 20:25 UTC, jiahe23 commented on .buildkite/pipeline.yml
> +    key: "cpu_schaer_mtn_2d_hybrid_invariant_total_energy_topography"
```suggestion
    key: "cpu_schar_mtn_2d_hybrid_invariant_total_energy_topography"
```

2022-12-13 20:32 UTC, bischtob commented
@akshaysridhar, can you please take a look at this?

2022-12-13 21:01 UTC, jiahe23 commented on examples/Manifest.toml
> +julia_version = "1.8.2"
Let's stay with 1.8.3?

2022-12-13 21:02 UTC, jiahe23 approved these changes
Looks good to me, unless @akshaysridhar wants to take a look before it is merged.

2022-12-14 00:06 UTC, simonbyrne commented on examples/hybrid/plane/topo_agnesi_nh.jl
> +
```suggestion
```
This can be removed

2022-12-14 00:06 UTC, simonbyrne commented on examples/hybrid/plane/topo_schar_nh.jl
> +
```suggestion
```
Same here

2022-12-14 00:07 UTC, simonbyrne requested changes
Since both files are pretty similar, can they be combined into one that can be run with different options?

2022-12-14 00:46 UTC, bischtob commented
> Since both files are pretty similar, can they be combined into one that can be run with different options?
Let's keep two files for now. We may just delete one later.

2022-12-14 00:47 UTC, bischtob commented
bors try

2022-12-14 19:35 UTC, simonbyrne commented
bors r+

2022-12-14 20:36 UTC, merged