Make dss and weighted_dss no-ops for empty fields.
CliMA/ClimaCore.jl pull request #1270
Opened 2023-05-25 22:45 UTC by sriharshakandala

Make dss and weighted_dss no-ops for empty fields.

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

2023-05-25 23:54 UTC, sriharshakandala commented
bors try

2023-05-26 02:54 UTC, sriharshakandala commented
bors try

2023-05-26 20:42 UTC, sriharshakandala commented on test/Spaces/ddss1.jl
> +    y0 = init_state_scalar.(Fields.local_geometry_field(space), Ref(nothing))
Sure!

2023-05-26 22:17 UTC, sriharshakandala commented
bors try

2023-05-26 22:17 UTC, simonbyrne requested changes

2023-05-26 22:17 UTC, simonbyrne commented on test/Spaces/ddss1.jl
> +    empty_field = Fields.Field(data, space)
Should be easier to do
```suggestion
    empty_field = similar(y0, Tuple{})
```

2023-05-26 22:18 UTC, simonbyrne commented
looks good other than the test change

2023-05-26 22:20 UTC, sriharshakandala commented
bors r-

2023-05-26 22:36 UTC, sriharshakandala commented
bors r+

2023-05-26 23:48 UTC, merged