Preliminary draft for optimize halo exchange.
CliMA/ClimaCore.jl pull request #965
Opened 2022-09-27 18:40 UTC by sriharshakandala

- [ ] Code follows the [style guidelines](https://clima.github.io/ClimateMachine.jl/latest/DevDocs/CodeStyle/) OR N/A.
- [ ] Unit tests are included OR N/A.
- [ ] Code is exercised in an integration test OR N/A.
- [ ] Documentation has been added/updated OR N/A.

2022-10-03 21:33 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function dss_local_ghost2!(perimeter_data, perimeter, topology)
does "local" part of ghost vertex dss (e.g. where 2 local elements share a vertex that needs to be computed). This is stored back in all locations in `perimeter_data`

2022-10-03 21:35 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function fill_send_buffer2!(dss_buffer::DSSBuffer)
loads send_buffer from perimeter_data

2022-10-03 21:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function dss_local2!(perimeter_data, perimeter, topology)
local dss, written back to perimeter

2022-10-03 21:41 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function load_from_recv_buffer2!(dss_buffer::DSSBuffer)
adds dss to representative element in perimeter

2022-10-03 21:41 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function dss_ghost2!(perimeter_data, perimeter, topology)
takes representative element, and sets all colocated vertices to same value

2022-10-03 21:42 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +function dss_untransform2!(
untransforms, and copies back

2022-10-03 21:53 UTC, simonbyrne commented on src/Topologies/dtopology2d.jl
> +    ghost_vertex_gidx::Vector{Int}
Can we call this `gcidx` (connection) to distinguish from element `gidx`?

2022-10-03 21:55 UTC, simonbyrne commented on src/Topologies/dtopology2d.jl
> +    comm_vertex_lengths::Vector{Int}
`comm_vertex_lengths[i]` = number of unique vertices to be communicated to `neighbor_pids[i]`

2022-10-03 22:02 UTC, simonbyrne commented on src/Topologies/dtopology2d.jl
> +    ghost_vertex_comm_idx_offset::Vector{Int}
a ragged array representation:
for `i = 1:length(ghost_vertex_gidx)`, we have that for `j = ghost_vertex_comm_idx_offset[i]:ghost_vertex_comm_idx_offset[i+1]-1`
the ghost vertex `ghost_vertex_gidx[i]` should get sent to `neighbor_pids[ghost_vertex_neighbor_loc[j]]`.

2022-10-13 22:38 UTC, simonbyrne commented on src/Topologies/dtopology2d.jl
> +    ghost_vertex_comm_idx_offset::Vector{Int}
include this in the docstring

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss.jl
> +include("dss2.jl")
move this include to `Spaces.jl`

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +    Transforms vectors from Covariant axes to physical (local axis),
don't indent this (it will render as code)

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +weights the data at perimeter nodes, and stores result in the perimeter_data array.
explain what all the arguments are

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +        @inbounds for (p, (ip, jp)) in enumerate(perimeter)
one `@inbounds is enough (it is applied syntactically to everything below)

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +        data::DataLayouts.VIJFH,
you only need one docstring for a function if all the methods do the same thing

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +Transforms the DSS`d local vectors back to Covariant12 vectors, and copies the DSS'd data from the
```suggestion
Transforms the DSS'd local vectors back to Covariant12 vectors, and copies the DSS'd data from the
```

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +Transforms the DSS`d local vectors back to Covariant12 vectors, and copies the DSS'd data from the
again, this docstring is redundant

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +Computes weighted dss of `data`.
Can you describe a bit more how it works, and link to the subfunctions?

2022-10-13 22:38 UTC, simonbyrne commented on src/Spaces/dss2.jl
> +Computes weighted dss of `data`.
Also, need to add all the docstrings to `docs/src/api.md`

2022-10-20 18:49 UTC, simonbyrne requested changes
Can you look at the docs, and fix the formatting and duplicated docstrings, e.g.
https://clima.github.io/ClimaCore.jl/previews/PR965/api/#ClimaCore.Spaces.dss_transform2!

2022-10-21 19:09 UTC, sriharshakandala commented
bors try

2022-10-24 16:51 UTC, simonbyrne commented on src/DataLayouts/DataLayouts.jl
> +function Base.iterate(data::DataLayouts.AbstractData{S}, ivar = 1) where {S}
If this isn't being used, perhaps remove it? I'm not sure that makes the most sense as a way to iterate.

2022-10-24 16:53 UTC, simonbyrne commented on src/Fields/Fields.jl
> +#----------test code
is this comment still relevant?

2022-10-24 21:07 UTC, simonbyrne approved these changes
LGTM. Squash the commits before merging.

2022-10-24 21:42 UTC, sriharshakandala commented
bors try

2022-10-24 22:31 UTC, sriharshakandala commented
bors r+

2022-10-24 22:50 UTC, simonbyrne commented
bors r+

2022-10-24 23:51 UTC, sriharshakandala commented
bors r+

2022-10-25 00:48 UTC, simonbyrne commented
bors r+

2022-10-25 02:29 UTC, merged